### ISSUE TITLE
Fix these dead links

### ISSUE THREAD

**Issue by MichelleGlauser** [Techtonica/curriculum#1122] opened 2020-01-07 17:22 UTC
Update:  
There are 20 or so links left un-checked in the original list below.  Your task is to:
1. Check that they truly do not work. If they work after all, or it's a misunderstanding (like when it flagged "something.com"), check them off.
2. Fix broken ones in a PR if its an easy URL fix.
3. Check off any links addressed in #s 1 and 2.
4. Make a neat list in the comments here of links that have truly dead pages, or they are somehow blocked. We will fix those in another issue.

Last, make a PR with `closes #1122` in the description.

See the original issue below.

__________________________

Following is a list of potential dead links as of 2020-01-07. Don't feel like you need to address every single one. Check off ones you've addressed and open a PR with the resolutions.

README.md
- [x] 105:4-105:127  warning  Link to https://github.com/Techtonica/curriculum/blob/master/javascript/event-recommender.md is dead                                                                             no-dead-urls  remark-lint
- [x] 105:4-105:127  warning  Link to unknown file: `javascript/event-recommender.md`                                                                                                                          missing-file  remark-validate-links
- [x] 106:4-106:142  warning  Link to https://github.com/Techtonica/curriculum/blob/master/javascript/event-recommender-part2.md is dead                                                                       no-dead-urls  remark-lint
- [x] 106:4-106:142  warning  Link to unknown file: `javascript/event-recommender-part2.md`                                                                                                                    missing-file  remark-validate-links

_templates/topic-outline.md
- [x] 15:12-15:93  warning  Link to unknown file: `version-control/git-version-control/git-version-control.md`. Did you mean `../git-version-control/git-version-control.md`                                 missing-file  remark-validate-links
- [x] 41:3-41:65  warning  Link to https://otherexample.com is dead                                                                                                                                         no-dead-urls  remark-lint
- [x] 48:3-48:54  warning  Link to unknown file: `google.com`                                                                                                                                               missing-file  remark-validate-links
- [x] 49:3-49:84  warning  Link to unknown file: `google.com`                                                                                                                                               missing-file  remark-validate-links
- [x] 90:3-90:52  warning  Link to https://otherexample.com is dead                                                                                                                                         no-dead-urls  remark-lint

agile-development/intro-to-agile.md
 - [x] 92:1-92:195  warning  Link to https://ekiy5aot90-flywheel.netdna-ssl.com/wp-content/uploads/2013/07/segue-blog-waterfall-vs-agile-which-is-right-development-methodology-for-your-project.png is dead  no-dead-urls  remark-lint
- [x] 126:3-126:69  warning  Link to http://www.scalingtheheights.com/complexity-theory-stacey-diagram/ is dead                                                                                               no-dead-urls  remark-lint
- [x] 243:3-243:93  warning  Link to https://www.scrumalliance.org/why-scrum is dead                                                                                                                          no-dead-urls  remark-lint

api/http-request-practice.md
- [x] 15:12-15:93  warning  Link to unknown file: `version-control/git-version-control/git-version-control.md`. Did you mean `../git-version-control/git-version-control.md`                                 missing-file  remark-validate-links
- [x] 41:3-41:65  warning  Link to https://otherexample.com is dead                                                                                                                                         no-dead-urls  remark-lint
- [x] 48:3-48:54  warning  Link to unknown file: `google.com`                                                                                                                                               missing-file  remark-validate-links
- [x] 49:3-49:84  warning  Link to unknown file: `google.com`                                                                                                                                               missing-file  remark-validate-links
- [x] 90:3-90:52  warning  Link to https://otherexample.com is dead                                                                                                                                         no-dead-urls  remark-lint

command-line/vim.md
- [x] 9:3-9:67  warning  Link to unknown file: `command-line/command-line-interface.md`                                                                                                                   missing-file  remark-validate-links

databases/relational-databases.md
- [x] 217:5-217:121  warning  Link to https://techdifferences.com/difference-between-mysql-and-postgresql.htmls is dead                                                                                        no-dead-urls  remark-lint

databases/sql-1.md
- [x] 7:3-7:42  warning  Link to unknown file: `databases/data-models.md`                                                                                                                                 missing-file  remark-validate-links

databases/sql-2.md
- [x] 7:3-7:50  warning  Link to unknown file: `databases/data-modeling-1.md`                                                                                                                             missing-file  remark-validate-links
- [x] 8:3-8:30  warning  Link to unknown file: `databases/sql-1.md`                                                                                                                                       missing-file  remark-validate-links
- [x] 9:3-9:50  warning  Link to unknown file: `databases/data-modeling-2.md`                                                                                                                             missing-file  remark-validate-links

databases/sql.md
- [x] 7:3-7:42  warning  Link to unknown file: `databases/data-models.md`                                                                                                                                 missing-file  remark-validate-links

debugging/debugging.md
- [x] 34:3-34:79  warning  Link to unknown file: `uu`                                                                                                                                                       missing-file  remark-validate-links

javascript/javascript-1.md
- [x] 19:180-19:204  warning  Link to unknown file: `www.meetup.com`                                                                                                                                           missing-file  remark-validate-links

javascript/javascript-2.md
- [x] 16:351-16:375  warning  Link to unknown file: `www.google.com`                                                                                                                                           missing-file  remark-validate-links

learning-to-learn/learning-to-learn.md
- [x] 82:10-82:94  warning  Link to http://mindsetonline.com/testyourmindset/step1.php is dead                                                                                                               no-dead-urls  remark-lint

navigating-new-codebases/navigating-new-codebases.md
- [x] 31:3-31:181  warning  Link to unknown file: `(https:/medium.com/humans-create-software/5-tips-to-quickly-understand-a-new-code-base-a578b08f3593)`                                                     missing-file  remark-validate-links

node-js/node-lab-exercise-part-2.md
- [x] 159:186-159:207  warning  Link to http://127.0.0.1:3000 is dead                                                                                                                                            no-dead-urls  remark-lint
- [x] 159:264-159:285  warning  Link to http://localhost:3000 is dead                                                                                                                                            no-dead-urls  remark-lint
- [x] 258:48-258:69  warning  Link to http://localhost:3000 is dead                                                                                                                                            no-dead-urls  remark-lint

objectives/9.md
- [x] 4:4-4:72  warning  Link to unknown file: `projects/react-assessment.md`. Did you mean `../projects/react-assessment.md`                                                                             missing-file  remark-validate-links
- [x] 15:4-15:65  warning  Link to unknown file: `projects/mongo-assessment.md`. Did you mean `../projects/mongo-assessment.md`                                                                             missing-file  remark-validate-links
- [x] 24:4-24:65  warning  Link to unknown file: `projects/auth0-assessment.md`. Did you mean `../projects/auth0-assessment.md`                                                                             missing-file  remark-validate-links

open-source/open-source.md
- [x] 20:10-20:103  warning  Link to unknown file: `(https:/www.datamation.com/amp/open-source/35-top-open-source-companies-1.html)`                                                                          missing-file  remark-validate-links
- [x] 21:15-21:108  warning  Link to unknown file: `(https:/www.datamation.com/amp/open-source/35-top-open-source-companies-1.html)`                                                                          missing-file  remark-validate-links

pair-programming/pair-programming.md
- [x] 66:143-66:218  warning  Link to https://codepen.io/ulfiw/pen/YQoQgx is dead                                                                                                                              no-dead-urls  remark-lint

professionalism/LinkedIn.md
- [x] 15:12-15:96  warning  Link to https://github.com/Techtonica/curriculum/blob/master/resume-writing/resume-writing.m is dead                                                                             no-dead-urls  remark-lint
- [x] 15:12-15:96  warning  Link to unknown file: `../resume-writing/resume-writing.m`. Did you mean `../resume-writing/resume-writing.md`                                                                   missing-file  remark-validate-links

projects/data-structures-algorithms-assessment.md
 - [x] 2:1-2:113  warning  Link to https://github.com/Techtonica/curriculum/blob/master/assessment-objectives/11.md is dead                                                                                 no-dead-urls  remark-lint
- [x] 2:1-2:113  warning  Link to unknown file: `../assessment-objectives/11.md`                                                                                                                           missing-file  remark-validate-links

projects/eventonica/eventonica-react.md
- [x] 5:30-5:145  warning  Link to unknown file: `../eventonica-project.md`. Did you mean `eventonica-project.md`                                                                                           missing-file  remark-validate-links
- [x] 38:93-38:115  warning  Link to http://localhost:5000" is dead                                                                                                                                           no-dead-urls  remark-lint
- [x] 38:93-38:115  warning  Link to unknown file: `http:/localhost:5000"`                                                                                                                                    missing-file  remark-validate-links

react-js/react-hooks.md
 - [ ] 15:12-15:93  warning  Link to unknown file: `version-control/git-version-control/git-version-control.md`. Did you mean `../git-version-control/git-version-control.md`                                 missing-file  remark-validate-links
- [x] 41:3-41:65  warning  Link to https://otherexample.com is dead                                                                                                                                         no-dead-urls  remark-lint
- [x] 48:3-48:54  warning  Link to unknown file: `google.com`                                                                                                                                               missing-file  remark-validate-links
- [x] 49:3-49:84  warning  Link to unknown file: `google.com`                                                                                                                                               missing-file  remark-validate-links
- [x] 90:3-90:52  warning  Link to https://otherexample.com is dead                                                                                                                                         no-dead-urls  remark-lint

react-js/react.md
- [ ] 15:1-15:29  warning  Link to unknown file: `www.facebook.com`                                                                                                                                         missing-file  remark-validate-links
- [ ] 38:4-38:76  warning  Link to http://codepen.io/marcacyr/pen/NAyqgX is dead                                                                                                                            no-dead-urls  remark-lint
- [ ] 39:4-39:80  warning  Link to http://codepen.io/marcacyr/pen/bZLVbj is dead                                                                                                                            no-dead-urls  remark-lint
- [ ] 40:4-40:72  warning  Link to http://codepen.io/marcacyr/pen/rLJVqR is dead                                                                                                                            no-dead-urls  remark-lint
- [ ] 41:4-41:95  warning  Link to http://codepen.io/marcacyr/pen/KrQpYb is dead                                                                                                                            no-dead-urls  remark-lint

redux/redux.md
- [ ] 29:3-29:75  warning  Link to http://codepen.io/marcacyr/pen/NAyqgX is dead                                                                                                                            no-dead-urls  remark-lint
- [ ] 30:3-30:79  warning  Link to http://codepen.io/marcacyr/pen/bZLVbj is dead                                                                                                                            no-dead-urls  remark-lint
- [ ] 31:3-31:71  warning  Link to http://codepen.io/marcacyr/pen/rLJVqR is dead                                                                                                                            no-dead-urls  remark-lint
- [ ] 32:3-32:94  warning  Link to http://codepen.io/marcacyr/pen/KrQpYb is dead                                                                                                                            no-dead-urls  remark-lint

requests-and-responses/_notes.md
- [ ] 19:5-19:79  warning  Link to http://royal.pingdom.com/2012/08/15/fun-and-unusual-http-response-headers/ is dead                                                                                       no-dead-urls  remark-lint

requests-and-responses/intro-to-dns-ip.md
- [ ] 60:31-60:113  warning  Link to https://royal.pingdom.com/2009/06/08/a-visual-explanation-of-how-dns-lookups-work/ is dead                                                                               no-dead-urls  remark-lint

roles-in-tech/qa.md
 - [x] 12:3-12:69  warning  Link to unknown file: `curriculum/testing-and-tdd/testing-and-tdd.md`. Did you mean `../testing-and-tdd/testing-and-tdd.md`                                                      missing-file  remark-validate-links

roles-in-tech/security.md
- [ ] 3:1-3:53  warning  Link to unknown file: `\roles-in-tech\security-locks.jpg`                                                                                                                        missing-file  remark-validate-links
- [ ] 17:268-17:383  warning  Link to https://www.thenetworkpro.net/2010/04/02/why-is-computer-security-important/ is dead                                                                                     no-dead-urls  remark-lint
- [ ] 65:30-65:139  warning  Link to https://wanguolin.github.io/assets/cryptography_and_network_security.pdf is dead                                                                                         no-dead-urls  remark-lint
- [ ] 140:7-140:78  warning  Link to https://www.themuse.com/jobs/eventbrite/security-engineer is dead                                                                                                        no-dead-urls  remark-lint
- [ ] 148:78-148:175  warning  Link to https://www.cloudflare.com/learning/security/glossary/what-is-penetration-testing/ is dead                                                                               no-dead-urls  remark-lint
- [ ] 196:3-196:48  warning  Link to https://twitter.com/Mikab0nita is dead                                                                                                                                   no-dead-urls  remark-lint
- [ ] 199:3-199:58  warning  Link to https://live.ncsc.gov.uk/information/about-ncsc is dead                                                                                                                  no-dead-urls  remark-lint

testing-and-tdd/integration-testing.md
- [x] 479:38-479:77  warning  Link to https://elephantsql.com/ is dead                                                                                                                                         no-dead-urls  remark-lint

testing-and-tdd/testing-and-tdd.md
- [x] 266:1-266:44  warning  Link to https://www.browserling.com/ is dead                                                                                                                                     no-dead-urls  remark-lint

**Comment by vegetabill** [comment] 2020-02-14 18:56
Obviously this list is long so fixing a few of them is much appreciated! 

Project maintainer note: in terms of prioritization, we should be encouraging participants to submit fixes for broken links they find rather than this sort of upfront approach. A broken link is less important to fix if it's in lower-priority content and not being actively clicked.

**Comment by alodahl** [comment] 2020-02-19 04:40
We found these with a bot, we are not listing them as we go or anything.

**Comment by abhinashgiri** [comment] 2020-02-27 17:30
I want to give this a try , if you all guide me. Please assign me this one.

**Comment by huonggiangbui** [comment] 2020-03-01 05:16
Can I take this issue? Really interested

**Comment by Kundan28** [comment] 2020-03-10 12:05
@vegetabill @alodahl Could this be worked under GSSoC20 ?

**Comment by hayjay-coder** [comment] 2020-03-12 23:12
I'm interested in this task can it be assigned to me from GSSoC20

**Comment by Kundan28** [comment] 2020-03-13 02:45
@hayjay-coder This issue don't have `gssoc20` label till now, so I would request you to have a look at other tasks.

**Comment by alodahl** [comment] 2020-03-15 02:27
@abhinashgiri would you like to work on this one?

**Comment by abhinashgiri** [comment] 2020-03-15 16:20
I already have two issues assigned now.So please assign it to someone else. Thank you

**Comment by pa7ri** [comment] 2020-03-15 19:58
I've just found another dead-link for the list inside [CONTRIBUTING.md](https://github.com/Techtonica/curriculum/blob/master/CONTRIBUTING.md) -> Step 1 -> Step 1: GSSoC Participants (last item) -> 'Style Guide' (just seen, itsn't done yet : https://github.com/Techtonica/curriculum/issues/596)

**Comment by alodahl** [comment] 2020-03-15 23:26
@huonggiangbui would you like this issue?

**Comment by alodahl** [comment] 2020-03-15 23:30
I'm going to assign the first responder.  How about you, @thisLinda ?

**Comment by thisLinda** [comment] 2020-03-16 01:28
Yes!

**Comment by Kundan28** [comment] 2020-03-16 02:10
Is @thisLinda a GSSoC participant ?

**Comment by huonggiangbui** [comment] 2020-03-16 04:48
@alodahl I would like to work on this issue

**Comment by pa7ri** [comment] 2020-03-16 12:31
I'm a GSSoC participant (just solved a previous assigned issue) and I would like to work on it, if possible

**Comment by thisLinda** [comment] 2020-03-16 22:41
Clarifying question regarding the instructions. Are the numbers supposed to indicate the line of code the issue is on? For instance:

react-js/react-hooks.md
 **48:3-48:54** warning Link to unknown file: google.com missing-file remark-validate-links
 **49:3-49:84** warning Link to unknown file: google.com missing-file remark-validate-links
If yes, there are no lines of code on lines 48 and 49. I know the code has changed quite a bit recently and perhaps the links are relatively near those numbers? In this case there's one link on each of these lines: 44, 45, 46, 51. Should they all be checked? 

If the numbers are not the lines of code, please tell me what they are.

**Comment by kichloo** [comment] 2020-03-17 10:37
@Kundan28 @alodahl I am a GSSOC participant, can I work on it?

**Comment by thisLinda** [comment] 2020-03-24 19:10
@alodahl @vegetabill Will this issue be assigned?

**Comment by alodahl** [comment] 2020-04-06 00:07
Sorry I missed this whole convo and made you wait! You can have it if you like, @thisLinda.

**Comment by thisLinda** [comment] 2020-04-06 16:58
Yes, I will complete it. Would someone please answer the question I asked (above, 21 days ago) to assure I'm understanding correctly. I had reviewed the remaining links--if I'm recalling correctly I think several may no longer exist.

**Comment by alodahl** [comment] 2020-04-09 02:04
Hi Linda, sorry I missed that comment.  

Yes, the numbers refer to the line that the link is on. These files are constantly being edited, so take the location with a grain of salt.. it may have moved over a line or two.

If it is clearly a fake example link, like google.com or otehrexample.com, we don't care about those. A lot of this ticket is checking the context to see whether the flagged link is really a problem. Please do address ones that seem like they should lead somewhere, like if the context is actually asking the apprentice to look at something on google.com.

**Comment by thisLinda** [comment] 2020-04-09 15:17
I was unable to check off the boxes, couldn't figure out how to do it. I would appreciate it if someone would let me know.
I have completed all and have submitted a pull request. Here is the "neat list" of truly dead pages:

> **react-js/react-hooks.md**
 15:12-15:93 warning Link to unknown file: version-control/git-version-control/git-version-control.md. Did you mean ../git-version-control/git-version-control.md missing-file remark-validate-links 
***NO SUCH LINK anywhere in repo

> **redux/redux.md**
***these LINKS ARE ALL ACTIVE but they are in react-js/react.md file (redux/redux.md no longer exists)

> **roles-in-tech/security.md**
 3:1-3:53 warning Link to unknown file: \roles-in-tech\security-locks.jpg missing-file remark-validate-links
***link now in career/roles-in-tech/security.md BAD/INCOMPLETE LINK for .jpg
 17:268-17:383 warning Link to https://www.thenetworkpro.net/2010/04/02/why-is-computer-security-important/ is dead no-dead-urls remark-lint
***no such link appears to have been replaced with another, similar link
 65:30-65:139 warning Link to https://wanguolin.github.io/assets/cryptography_and_network_security.pdf is dead no-dead-urls remark-lint
***NO SUCH LINK anywhere in repo
 140:7-140:78 warning Link to https://www.themuse.com/jobs/eventbrite/security-engineer is dead no-dead-urls remark-lint
***DEAD LINK, now in career/roles-in-tech/security.md
 148:78-148:175 warning Link to https://www.cloudflare.com/learning/security/glossary/what-is-penetration-testing/ is dead no-dead-urls remark-lint
***NO SUCH LINK anywhere in repo
 196:3-196:48 warning Link to https://twitter.com/Mikab0nita is dead no-dead-urls remark-lint
***DEAD LINK, now in career/roles-in-tech/security.md
 199:3-199:58 warning Link to https://live.ncsc.gov.uk/information/about-ncsc is dead no-dead-urls remark-lint
***DEAD LINK, now in career/roles-in-tech/security.md

**Comment by alodahl** [comment] 2020-04-09 15:36
I added you as a project contributor, which may allow you to check the boxes.  Thank you Linda!

**Closed** 2020-04-09 15:37 UTC
Labels: EASY, no-eng-required, not-for-gssoc

**Comment by thisLinda** [comment] 2020-04-09 16:33
I am still unable to check the boxes :(
