### ISSUE TITLE
ensure all 'let' and 'const' declarations are used correctly

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#1195] opened 2020-02-23 16:47 UTC
# Task:

Search through the curriculum project, and double check that all of the code examples are using `let` and `const` correctly, so apprentices can see it used correctly as they learn. If something is declared as `let` but it does not change anywhere in that lesson, be sure to change it to `const` in a pull request. Same thing for if something is declared as `const` does change.

**Comment by alti21** [comment] 2020-02-25 02:22
Hi can a try this?

**Comment by Kundan28** [comment] 2020-02-25 02:55
@alti21 Are you participating through GSSoC20 ?

**Comment by alti21** [comment] 2020-02-25 03:08
No I am not actually

**Comment by Kundan28** [comment] 2020-02-25 03:09
Okay, then @alodahl will guide you if you could work on this issue or not as it's marked with the label GSSoC20

**Comment by Tahanima** [comment] 2020-02-25 08:25
Hello, 
I am a GSSoC20 participant and I want to work on this issue.

**Comment by Kundan28** [comment] 2020-02-26 02:46
Okay, you can @Tahanima but make sure to make Pull Request only after 1st March.

**Comment by Kundan28** [comment] 2020-02-26 02:47
@alodahl please assign @Tahanima to this issue.

**Comment by Tahanima** [comment] 2020-02-26 03:57
Thank You @Kundan28

**Comment by Tahanima** [comment] 2020-02-29 15:23
@alodahl I have already filled in the Techtonica Volunteer Application. So, please assign this issue to me. Thanks.

**Comment by vegetabill** [comment] 2020-02-29 23:42
@Tahanima I have already assigned you to a different issue.

**Comment by gauravdas9343** [comment] 2020-03-01 01:38
Please assign me this issue if available?

**Comment by gauravdas014** [comment] 2020-03-01 01:40
Please assign me this issue if available?

**Comment by Kundan28** [comment] 2020-03-01 01:42
@gauravdas014 Could you please wait till @Tahanima confirms if she want t work on this issue or any other. If she wants to continue with the other one then I would be good to assign you to this issue.

**Comment by gauravdas014** [comment] 2020-03-01 01:42
Sure, no problem.

**Comment by Tahanima** [comment] 2020-03-01 03:25
Hello, 
Since I already confirmed to work on the other issue I'll stick to it. @vegetabill  @Kundan28 you can assign this issue to someone else. Thanks.

**Comment by Kundan28** [comment] 2020-03-01 03:28
@gauravdas014 

Thanks for volunteering to help Techtonica improve its curriculum!

Please follow the [contribution instructions](https://github.com/Techtonica/curriculum/blob/master/CONTRIBUTING.md#step-0) in additional to any instructions from GSSoC.

Questions?
If you have any question about this issue and what contributions are being asked for, reply on this issue.
If you have questions about Git, Pull Requests, GitHub, or the contest itself, talk to a mentor (M) in Slack. Questions of that nature posted here will not be answered.

**Comment by manan-bedi2908** [comment] 2020-03-01 10:39
I would like to work on this issue

**Comment by Kundan28** [comment] 2020-03-01 14:44
@manan-bedi2908 This issue is already assigned to someone else, so I would request you to please go for some other issue.

**Comment by gauravdas014** [comment] 2020-03-01 19:51
@Kundan28 Do I need to change the "var" (s) as well? in the issue, it is only mentioned that check the const and let.

**Comment by vegetabill** [comment] 2020-03-01 19:57
@Kundan28 `var` is being removed in a different issue so you do not have to review those.
#1197

**Closed** 2020-03-05 17:50 UTC
Labels: EASY, gssoc20
