### ISSUE TITLE
Revise HTTP request practice lesson

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1199] opened 2020-02-23 19:29 UTC
In the [/api/http-request-practice.md](https://github.com/Techtonica/curriculum/blob/master/api/http-request-practice.md) lesson we added too many options (6), including ones that are much less important. Let's simplify.

## Remove these sections

- XMLHttpRequest
- http.request in Node.js
- fetch in node

That means we're keeping curl, fetch (browser), and Postman.

## Add this link to the fetch section
Add it as an additional practice option.

https://www.freecodecamp.org/news/a-practical-es6-guide-on-how-to-perform-http-requests-using-the-fetch-api-594c3d91a547/

## Test out the content
Go through the lesson and time yourself. If your time is different than the estimate at the top, please update it.

**Comment by vegetabill** [comment] 2020-02-23 19:31
@boocheet please add any revision suggestions you have

**Comment by LovepreetSingh12** [comment] 2020-02-25 17:37
I am a beginner but i want to give this a try as a part of GSSoC 20.

**Comment by vegetabill** [comment] 2020-02-26 14:48
@LovepreetSingh12 thanks for offering to help. Before doing anything else please follow the steps in https://github.com/Techtonica/curriculum/blob/master/CONTRIBUTING.md#volunteering

**Comment by boocheet** [comment] 2020-02-26 17:12
1. Have a brief explanation and an example of GET request such as the GET request is only done by the user or client-side to request information i.e. going to www.google.com and the server-side sends the response by taking you to google's website. 
2. explain the syntax for sending a request, for example, request-method-name: HTTP protocol defines a set of request methods, e.g., GET, POST, HEAD, and OPTIONS. The client can use one of these methods to send a request to the server.
3.Have a guided practice of completing a request, for example, I have provided a link. https://www.freecodecamp.org/news/a-practical-es6-guide-on-how-to-perform-http-requests-using-the-fetch-api-594c3d91a547/

**Comment by vegetabill** [comment] 2020-02-28 14:11
@LovepreetSingh12 I've assigned this to you and updated the description. If you have any further questions, please ask here

**Comment by soulhunter10737** [comment] 2020-02-29 03:38
Hello, I am participant of GSSoC'20. Can you please assign me this issue? I would like to work on this.

**Comment by vegetabill** [comment] 2020-02-29 14:30
@soulhunter10737 the issue was already assigned when you commented. find an unassigned issue you are interested in instead

**Comment by Kundan28** [comment] 2020-03-14 13:24
@LovepreetSingh12 If you don't reply by tomorrow, the issue will be assigned to someone else.

**Comment by daya2940** [comment] 2020-03-14 15:53
i would like to work on this issue

**Comment by Kundan28** [comment] 2020-03-15 02:16
> i would like to work on this issue

Let's wait by today EOD and if we don't get any response from @LovepreetSingh12 the issue will be assigned to you.

**Comment by LovepreetSingh12** [comment] 2020-03-16 12:14
My sincere apologies. I was a bit busy because of my mid-semester examination. Now I'm free to do all the contributions

**Comment by Kundan28** [comment] 2020-03-16 16:35
> My sincere apologies. I was a bit busy because of my mid-semester examination. Now I'm free to do all the contributions

Please make the contribution as soon as possible as you were given 2 weeks.

**Comment by kichloo** [comment] 2020-03-17 10:28
@Kundan28 As the issue is now unassigned, pl give it to me!

**Comment by Kundan28** [comment] 2020-03-17 19:29
@kichloo thanks for offering to help. Before doing anything else please follow the steps in https://github.com/Techtonica/curriculum/blob/master/CONTRIBUTING.md#volunteering

**Comment by kichloo** [comment] 2020-03-18 05:35
@Kundan28 Do we have to keep `window.fetch` - Time API section or not?

**Comment by kichloo** [comment] 2020-03-18 05:41
And the sections removed have guided practice and independent practice questions associated with them, so the whole section of the question has to be removed?

**Comment by Kundan28** [comment] 2020-03-18 12:18
> @Kundan28 Do we have to keep `window.fetch` - Time API section or not?

No we don't have to keep it.

**Comment by Kundan28** [comment] 2020-03-18 12:19
> And the sections removed have guided practice and independent practice questions associated with them, so the whole section of the question has to be removed?

Yeah, everything related to the removed stuff should be removed.

**Comment by kichloo** [comment] 2020-03-18 13:55
@Kundan28 Done.

**Comment by kichloo** [comment] 2020-03-19 16:00
@Kundan28 Pl review the PR

**Closed** 2020-03-29 17:25 UTC
Labels: BEGINNER, Close to expiring, gssoc20
