### ISSUE TITLE
Revise REST API lesson

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1191] opened 2020-02-20 14:33 UTC
The previous two iterations of the [REST API lesson](/api/REST-API.md) were overly theoretical and assumed the reader already knew a lot about API's. Volunteers and participants both have said the lesson is not helpful the way it is now, so let's revise it.

- Remove examples of REST vs non-REST (since we won't be building any non-REST API's in Techtonica, for our purposes API === REST API)
- Link to some docs of some nicely documented REST API's (maybe GitHub?)
- Guided practice of building a very simple API
  - here is an [example of one](https://github.com/zhagm/Techtonica-assignments/commit/e48621789fc2b8abb900c02083ef35fa5a4b2c47) an apprentice built to teach others
- Show code snippets using Express
- Cover the semantics of the verbs, especially PUT vs POST
- Favor guided practice over definitions or explanations - this is a topic more than most where learning by doing is key

For FAQs on how to contribute, see: https://github.com/Techtonica/curriculum/blob/main/CONTRIBUTING.md

**Comment by vegetabill** [comment] 2020-02-20 14:33
@zhagm I used your express party as a possible practice lesson for this! 😁

**Comment by abhu-A-J** [comment] 2020-02-29 19:18
@vegetabill would like to take this one for GSSoC'20 . Can you assign it to me.?

**Comment by sonali623** [comment] 2020-03-01 08:33
I would like to take this issue as a part of GSSoC 2020,@vegetabill please assign this to me

**Comment by abhu-A-J** [comment] 2020-03-02 14:26
@Kundan28 @vegetabill @alodahl I would like to take if it's under as GSSoC participant

**Comment by Kundan28** [comment] 2020-03-02 14:28
It does not have GSSoC20 label, so @alodahl or @vegetabill would guide you. The issue is not assigned to you yet.

**Comment by abhu-A-J** [comment] 2020-03-02 14:29
@Kundan28 Sure. Will Wait.

**Comment by vegetabill** [comment] 2020-03-04 03:58
@abhu-A-J this will not be available as part of GSSoC20. The `subject-matter-expert` label indicates it needs input for an experienced engineer, not a student.

**Comment by Kundan28** [comment] 2020-03-05 01:41
Thanks for the clarification @vegetabill

**Comment by alodahl** [comment] 2020-06-19 00:44
I found a good intro lesson: https://www.freecodecamp.org/news/building-a-simple-node-js-api-in-under-30-minutes-a07ea9e390d2/

**Comment by sylvaindessureault** [comment] 2020-11-04 00:17
@vegetabill @alodahl 
I'd love to work on this!

**Comment by vegetabill** [comment] 2020-11-04 00:25
@sylvaindessureault go for it! It's definitely related to your other PR.

**Comment by sylvaindessureault** [comment] 2020-11-04 00:35
Excellent! I will start working on this!

**Comment by sylvaindessureault** [comment] 2020-11-06 04:29
@vegetabill and @alodahl, let me know if you need any changes!

**Closed** 2020-11-16 20:07 UTC
Labels: Hacktoberfest, MEDIUM, good-first-issue, pinned
