### ISSUE TITLE
change all instances of `var` to `let` or `const`

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#1197] opened 2020-02-23 17:22 UTC
# Task:

As of ES2015, the use of `var` is not recommended to declare variables, and we want our apprentices to avoid it.  Search through the curriculum, and change all instances of `var` to either `let` or `const`, whichever would be most correct. Submit your changes in a pull request.

**Comment by navi532** [comment] 2020-02-23 18:17
I want to contribute it.

**Comment by alodahl** [comment] 2020-02-23 20:23
Hi Navi, that’s great! Since we’re a non-profit, please fill [this](https://docs.google.com/forms/d/e/1FAIpQLSeW0mo-Dpsig70374UEPvzexpas-31Ost_HsFwm0kjNOxtbtg/viewform?c=0&w=1) out before you get started. Also, are you part of gssoc?

**Comment by navi532** [comment] 2020-02-24 09:27
Yes. I have taken part in GSSOC2020

**Comment by abhinashgiri** [comment] 2020-02-24 10:40
I too want to work on this. May I?

**Comment by Kundan28** [comment] 2020-02-25 02:51
@abhinashgiri Only one person can work on single issue until multiple contributors are not required. So better to search for other issue and work on it.

**Comment by Kundan28** [comment] 2020-02-25 02:53
@alodahl I'm the project mentor of this project as per GSSoC20 so why am I not getting notification as last time when someone comments on issue ?

**Comment by Kundan28** [comment] 2020-02-25 03:04
@alodahl The project admin has not joined the slack group till now. So if @vegetabill is not available for it I recommend you to join as the participants want to know about this project in dept.

**Comment by prangya244** [comment] 2020-02-29 15:08
I want to work on this issue and contribute as a part of GSSOC2020.

**Comment by Kundan28** [comment] 2020-03-01 01:56
@prangya244 The issue is already assigned to @navi532

**Comment by ravireddy07** [comment] 2020-03-05 10:20
@Kundan28  I would like to continue this issue, please assign this to me.

**Comment by Kundan28** [comment] 2020-03-06 02:01
@ravireddy07 The issue is already assigned to someone else.

**Comment by Kundan28** [comment] 2020-03-06 02:02
@navi532 You only have 3 days left for contributing to this particular issue. If we don't get any response from your side then someone else would be assigned to this issue.

**Comment by me-bhavya** [comment] 2020-03-12 14:17
Sir I would like to work on this issue as part of GSSOC 2020, please assign this to me.

**Comment by Kundan28** [comment] 2020-03-12 15:29
@me-bhavya You could not start working on this issue.

**Closed** 2020-03-28 20:04 UTC
Labels: EASY, gssoc20
