### ISSUE TITLE
more information on integrating express with react

### ISSUE THREAD

**Issue by lizandry** [Techtonica/curriculum#1251] opened 2020-03-05 00:27 UTC
https://github.com/Techtonica/curriculum/blob/master/projects/eventonica/eventonica-react.md

I hit a huge stumbling block when trying to get my express server to run my react code. It wouldn't render anything, then it wouldn't let me use ES6 syntax, then it (very) briefly wouldn't let me use ES5 syntax!

I believe the problem has to do with the create-react-app missing some Babel packages. But I got through it with the help of this article: https://medium.com/@danlegion/react-server-side-rendering-with-express-b6faf56ce22

**Comment by gauravdas014** [comment] 2020-03-05 06:30
Can I work on this issue under GSSoC?

**Comment by vegetabill** [comment] 2020-03-05 14:45
@lizandry if the problem is babel packages in [create-react-app](https://github.com/facebook/create-react-app), did you try searching open issues there? What made you think that was the case?

Did you enable server rendering? By default, CRA doesn't enable that so I'm wondering why the solution would involve something disabled.

**Comment by vegetabill** [comment] 2020-03-19 20:22
@lizandry can you update if this is still relevant. Is the workaround using that PREFLIGHT env variable? @boocheet was also seeing it. If so let's just link that in here and close this.

**Closed** 2020-05-10 22:05 UTC
Labels: pending-response, wontfix
