### ISSUE TITLE
Show apprentices how to authorize a user with Auth0 with existing example.

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#583] opened 2019-02-13 00:28 UTC
We need a short outline, slideshow, and video to show apprentices how to authorize a user with Auth0. We have a project, but your task is to guide apprentices through the key parts of the concepts and implementation.

They already learned how to add Auth0 for *authentication* [in this lesson](https://github.com/Techtonica/curriculum/blob/master/oauth/o-auth.md) and [this slideshow](https://docs.google.com/presentation/d/18f-1EbjxLXyxuRoXNekpJ_o-pI1uiBzJxFw9ZoaNuVM/edit?usp=sharing), but we need resources for how to use a token to *authorize* the user to access their own profile data.

- [ ] Save an outline in [this file](https://github.com/Techtonica/curriculum/blob/master/oauth/authorization.md) using the old lesson’s template as a guide.
- [ ] Save a visual version of your lesson in [this slideshow](https://docs.google.com/presentation/d/1mBXA2GqsARbR_LsouEEshNM5JvnQjDmrSXWhVeilfpc/edit?usp=sharing).
- [ ] Find or make a video that makes the same points as the outline and slides, and add a link to the "materials" section in the outline.

Use this project as your resource unless you find another one that’s a better fit:https://github.com/gsong/auth0-react-express-example

- Link it if it’s simply used as an example. However, if you think we could use it as the main lesson, please copy it over to our curriculum repo and clearly cite the original source.

For FAQs on contributing, see https://github.com/Techtonica/curriculum

**Comment by NirmalKumarJoshi** [comment] 2019-02-15 16:45
@alodahl I would like to take on this issue under GSSoC'19. Please guide me for the same.

**Comment by alodahl** [comment] 2019-02-15 20:58
Thank you, @NirmalKumarJoshi !  First, have you had a chance to fill out this volunteer form?:
https://docs.google.com/forms/d/e/1FAIpQLSeW0mo-Dpsig70374UEPvzexpas-31Ost_HsFwm0kjNOxtbtg/viewform?c=0&w=1

After that, please follow the follow the template to add directions for adding user authorization to a node/js or node/react project to [this topic outline file](https://github.com/Techtonica/curriculum/blob/master/oauth/authorization.md), and make a PR when you're ready for review.  Screenshots of the process would be very helpful to apprentices, and you can add them to [this slideshow](https://docs.google.com/presentation/d/1p7fa20o7lRyvXuXhsFz8MfHktY5MaqSPSrLdNjocNcE/edit?usp=sharing).

**Comment by Kundan28** [comment] 2019-03-06 04:52
Hi  @NirmalKumarJoshi , I wanted to check in to see how the task is going. Do you have any questions?

**Comment by ANURADHAJHA99** [comment] 2019-03-08 16:14
@Kundan28 If someone is not working on the following issue, I would like to take it.

**Comment by alodahl** [comment] 2019-03-08 17:21
Hi @ANURADHAJHA99 , please check “assignees” to see if someone has taken an issue. If it is in progress, it is definitely not available. @NirmalKumarJoshi has this one.

**Comment by alodahl** [comment] 2019-03-08 17:22
I’ll keep you in mind, though, @ANURADHAJHA99

**Comment by ANURADHAJHA99** [comment] 2019-03-08 17:24
Okay sure! Thank you.

**Comment by ANURADHAJHA99** [comment] 2019-03-08 17:26
Actually, I saw the due date and I thought maybe the issue is stray.

**Comment by alodahl** [comment] 2019-03-18 14:35
Hi @NirmalKumarJoshi , are you still working on this issue?

**Comment by alodahl** [comment] 2019-03-22 01:09
Hi @nirmalkumarjoshi, if we don’t hear from you by the end of the week, we will make this issue available to other gssoc contributors.

**Comment by ANURADHAJHA99** [comment] 2019-03-26 09:08
@alodahl can i work on this issue?

**Comment by ANURADHAJHA99** [comment] 2019-04-06 14:59
@alodahl  I have edited the presentation.Please kindly check on it. 
https://docs.google.com/presentation/d/1UtEz_IvRzcN8Jj2qj-8Kl4Q6yCYMKHM9sj607Awmx_c/edit#slide=id.g22b045fc2c_0_8

**Comment by alodahl** [comment] 2019-04-07 03:17
Looking good so far ... my first comment would be, please look at #600 for slide formatting guidelines, and also please check out PR #602 for the changes we requested from Nirmal before he disappeared!

**Comment by alodahl** [comment] 2019-04-07 03:24
Also, I’d hate to make your work in vain, but have you looked at the lesson that this is supposed to be continuing? It’s linked in the description. The learner has already started an app an learned how to set up authentication... the purpose of this lesson is to understand authentication and fetching user profile data, which you seem to address 8n the second half here.

**Comment by vsharma20v** [comment] 2019-04-26 12:34
@ANURADHAJHA99 are you still working on this issue?

**Comment by saberprashant** [comment] 2019-04-28 15:41
Hi @ANURADHAJHA99 , please reply to this one, because if you are busy with some other issue, then we can assign this to @vsharma20v .
@alodahl

**Comment by saberprashant** [comment] 2019-04-29 07:05
Hi @vsharma20v , thanks for your patience, but @ANURADHAJHA99 confirmed me on Slack that she is working on this issue. So, we can't assign you this one right now.
Thanks :)

**Comment by alodahl** [comment] 2019-04-30 01:26
@ANURADHAJHA99 you have had this issue for a month,  how much longer do you think you’ll need? If it’s past the new due date of May 3, please make a PR of what you have so someone else can work on it.

**Comment by Kundan28** [comment] 2019-04-30 03:52
> @ANURADHAJHA99 you have had this issue for a month, how much longer do you think you’ll need? If it’s past the new due date of May 3, please make a PR of what you have so someone else can work on it.

And if you need some more time you can comment down here or in the slack channel instead of just silently working on it without giving any update.

**Comment by vsharma20v** [comment] 2019-05-01 05:53
> Hi @vsharma20v , thanks for your patience, but @ANURADHAJHA99 confirmed me on Slack that she is working on this issue. So, we can't assign you this one right now.
> Thanks :)

Actually, I'm also busy with my End Semester Exams 
So I also can't work on this issue.
But I will come back after 7th May to claim new issue

**Comment by saberprashant** [comment] 2019-05-20 18:27
Hi @vsharma20v , would you like to work on this one now?

**Comment by gsong** [comment] 2020-01-07 16:47
This sample project I did for the last cohort seems relevant: https://github.com/gsong/auth0-react-express-example

**Comment by Kundan28** [comment] 2020-01-07 17:39
> This sample project I did for the last cohort seems relevant: https://github.com/gsong/auth0-react-express-example

Yeah, it is relevant.

**Comment by alodahl** [comment] 2020-01-19 20:39
How relevant is it? Should we i corporate that code into our curriculum repo? Should we link to it? Does it fulfill the issue ACs, or is it a partial solution?

**Comment by gsong** [comment] 2020-01-19 20:42
@alodahl It's a complete example as of last cohort, if by "Node.js," you mean "Express." The pattern is the same for other API servers, but implementation may differ drastically.

As for how you want to use it, it's up to you. I don't really care if you end up linking or copying it wholesale, it's all available as open source.

**Comment by alodahl** [comment] 2020-01-20 01:42
Thank you @gsong !

**Comment by Kundan28** [comment] 2020-01-20 04:04
@alodahl Call for Projects is open for GSSoC'20 so if you're interested please add your project. I'm ready to become mentor for this project as earlier.

**Comment by vegetabill** [comment] 2020-01-21 15:07
Removing priority label since this is part of the "Electives" now

**Comment by alodahl** [comment] 2020-01-23 01:56
@Kundan28 maybe!  Do you know the sign-up deadline?

**Comment by Kundan28** [comment] 2020-01-23 03:34
I think it's closed today.

**Comment by Kundan28** [comment] 2020-01-23 03:53
But if you want to signup...you could contact them.

**Comment by Kundan28** [comment] 2020-01-24 13:35
@alodahl I just gone though the site and saw the project submission is still open. So you want to submit please do so.

**Comment by Kundan28** [comment] 2020-01-25 03:53
@alodahl Last date is 25th January 2020.

**Comment by vegetabill** [comment] 2020-02-18 17:54
Since this is now an elective, I don't think we need to create this original content. It will be used in the project phase when participants should be able to find their own tutorials out there in the world.

**Closed by vegetabill** 2020-02-18 17:54 UTC
Labels: HARD
